# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dee152e116b861f8418070adb5467e3a0b3e5b71d45fa13955b9ced097f4bdfadffe46ddedcbd3098d4ad53dac60422f8e671cc2fae983e777eac32bb9e6f94

test:
  secret_key_base: f3a12c09950c23b4080b4f08e01c2483a66bd2ee8abfe3d9ce7542833849598665a1ad45d877c44c6e59029f5ad60ddc38571d46d1ab7fd3903e6923f9acd26b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
